### ISSUE TITLE
Automated CI

### ISSUE THREAD

**Issue by engnadeau** [kaustubh-sadekar/OmniCV-Lib#12]
There is currently no automated testing and deployment of the codebase. For this to be considered, a CI/CD setup (e.g., GitHub Actions) should be created that tests PRs, creates releases, and deploys to PyPI

cc https://github.com/openjournals/joss-reviews/issues/2533

**Comment by kaustubh-sadekar** [comment]
I have completed writing tests using standard testing frameworks based on your suggestions. I should be able to complete the CI/ CD setup within this week.

**Comment by kaustubh-sadekar** [comment]
The repository now supports automated testing and deployment. I have created all the CI/CD workflows as per your suggestion. Kindly let me know if further modifications are required or it is fine to close the issue tracker.

**Comment by engnadeau** [comment]
Why is there both `.github/workflows/buildPython.yml` and `.github/workflows/testsPython.yml`? They're almost duplicates

**Comment by engnadeau** [comment]
Also, `.github/workflows/testsCpp.yml` should have a separate step for building and testing the C++. It's currently lumped into `- name: Install dependencies` which makes it impossible to read: https://github.com/kaustubh-sadekar/OmniCV-Lib/runs/1242220788?check_suite_focus=true
