### ISSUE TITLE
Simplify entrypoint

### ISSUE THREAD

**Issue by engnadeau** [kaustubh-sadekar/OmniCV-Lib#14]
When getting started with the repo, the two primary entrypoints are "building the code" and "running examples".

While a skilled developer will have no problem building with cmake, running `chmod +x tests/test.sh`, and understanding what is needed to run the examples, these are an extra impedance for someone new to the repo.

I'd recommend using a `Makefile` as the entrypoint for building, running tests, etc. The READMEs will need to be updated as well.

cc https://github.com/openjournals/joss-reviews/issues/2533

**Comment by kaustubh-sadekar** [comment]
@nnadeau I would like to kindly convey to you that the issue has been resolved by creating Makefiles and also updating the documentation accordingly. Kindly provide your further reviews so we could decide if the thread could be closed.

**Comment by engnadeau** [comment]
New related issues: https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/28 https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/24 https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/23 https://github.com/kaustubh-sadekar/OmniCV-Lib/pull/22 https://github.com/kaustubh-sadekar/OmniCV-Lib/pull/21  https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/20 https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/19 https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/18
