### ISSUE TITLE
Shebang vs instructions

### ISSUE THREAD

**Issue by engnadeau** [kaustubh-sadekar/OmniCV-Lib#15]
The README instructions call for `bash test.sh` but the shebang in `test.sh` calls for `sh`. These are not the same. Moreover, calling `bash` on a file isn't standard practice. Rather the permissions should be updated so that we call the file like this: `./test.sh` (see #7 )

cc https://github.com/openjournals/joss-reviews/issues/2533

**Comment by engnadeau** [comment]
To be honest, `test.sh` should be fully replaced by a `Makefile` and the tests should be called using `make test` and `make test-gui` commands. See #14

**Comment by kaustubh-sadekar** [comment]
@nnadeau based on your valuable suggestions I have created a single Makefile and have provided several options to the user to build and run the tests. All the options have been explained in the installation instructions here : https://pypi.org/project/omnicv/

**Comment by engnadeau** [comment]
Please also update `docs/_sources/index.rst.txt`
