### ISSUE TITLE
Testing doesn't use testing frameworks

### ISSUE THREAD

**Issue by engnadeau** [kaustubh-sadekar/OmniCV-Lib#16]
All the tests, whether C++ or Python, aren't using modern, tested, and robust testing frameworks. For Python, I personally recommend `pytest`. For C++, I personally recommend `Catch2`.

This should also be integrated with #12 

cc https://github.com/openjournals/joss-reviews/issues/2533

**Comment by kaustubh-sadekar** [comment]
Thank you so much for all the suggestions and guidance. It's my first JOSS paper and it's a great learning experience for me. I will definitely improve the test process keeping all the suggestions in mind as early as possible.

**Comment by kaustubh-sadekar** [comment]
I have updated the test files based on your suggestions.

**Comment by kaustubh-sadekar** [comment]
I have further modified the testing files and used `pytest` and `Catch2`. Please let me know if it is as per requirements and if we could close the issue.

cc openjournals/joss-reviews#2533

**Comment by engnadeau** [comment]
@kaustubh-sadekar good start, but there's still some work to do. Please see https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/26 https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/23 for additional issues.

**Comment by engnadeau** [comment]
Also, `pytest` should be called simply by running `pytest` in the root folder (see the documentation for proper usage: https://docs.pytest.org/en/stable/)
