### ISSUE TITLE
Contribution and authorship

### ISSUE THREAD

**Issue by engnadeau** [kaustubh-sadekar/OmniCV-Lib#2]
- The [paper](https://github.com/kaustubh-sadekar/OmniCV-Lib/blob/master/paper/paper.md) lists Leena Vachhani and Abhishek Gupta as co-authors. There is no commit history that includes anyone but @kaustubh-sadekar contributing to the code.

How were these authors involved in developing this codebase?

Remember, with JOSS co-authorship is not awarded to supervisors: https://joss.readthedocs.io/en/latest/submitting.html#authorship

cc https://github.com/openjournals/joss-reviews/issues/2533

**Comment by kaustubh-sadekar** [comment]
There were several active non-code contributions from both the CO-authors towards shaping the OmniCV library. Their active direction in terms of designing the architecture of the library, deciding various functionalities of OmniCV that would be useful for robotics research based on useful reference, deciding the architecture of ROS nodes, developing the design and flow of the entire OmniCV documentation as well as the OmniCV paper. Hence active contributions from both the CO-authors have a significant role in transforming OmniCV from a small piece of unstructured code to a complete library with several useful features.

**Comment by engnadeau** [comment]
@mjsottile , i'll leave it to you as the editor to determine the suitability of co-authorship with respect to https://joss.readthedocs.io/en/latest/submitting.html#authorship

**Comment by mjsottile** [comment]
Based on what @kaustubh-sadekar stated about their role, their contributions sound like they fit the requirements stated in the JOSS documents - active direction and non-code contributions are acceptable for inclusion as co-authors.  There is no requirement that all authors appear in the git commit history.  Their co-authorship role looks fine to me.
