### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by engnadeau** [kaustubh-sadekar/OmniCV-Lib#5]
- bad comma in https://github.com/kaustubh-sadekar/OmniCV-Lib/blob/master/paper/paper.md : ` to, simulate virtual `
- other minor syntax issues

cc https://github.com/openjournals/joss-reviews/issues/2533

**Comment by kaustubh-sadekar** [comment]
Thank you very much for the suggestions. I have updated paper.md file.
